title: My Data Science Portfolio
email: mdvmurray@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio showcasing my projects and skills in data science, machine learning, and AI.
url: "https://micahmurray.github.io" # the base hostname & protocol for your site

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
